import type { UpgradeSourceConfig } from './upgradeTypes';

export const UPGRADE_SOURCES: Record<string, UpgradeSourceConfig> = {
  BTC:   { github: 'bitcoin/bitcoin',                    blog_rss: 'https://bitcoin.org/en/rss/releases.rss',          coinmarketcal_id: '1' },
  ETH:   { github: 'ethereum/go-ethereum',               blog_rss: 'https://blog.ethereum.org/feed.xml',               coinmarketcal_id: '1027' },
  SOL:   { github: 'anza-xyz/agave',                     blog_rss: 'https://solana.com/news/rss.xml',                  coinmarketcal_id: '5426' },
  LINK:  { github: 'smartcontractkit/chainlink',         twitter: 'chainlink',                                         coinmarketcal_id: '1975' },
  AVAX:  { github: 'ava-labs/avalanchego',               blog_rss: 'https://medium.com/feed/avalancheavax',            coinmarketcal_id: '5805' },
  DOT:   { github: 'paritytech/polkadot-sdk',            blog_rss: 'https://polkadot.network/blog/rss.xml',            coinmarketcal_id: '6636' },
  MATIC: { github: 'maticnetwork/bor',                   twitter: '0xPolygon',                                         coinmarketcal_id: '3890' },
  ARB:   { github: 'OffchainLabs/nitro',                 blog_rss: 'https://medium.com/feed/offchainlabs',             coinmarketcal_id: '11841' },
  OP:    { github: 'ethereum-optimism/optimism',         blog_rss: 'https://optimism.mirror.xyz/feed.rss',             coinmarketcal_id: '11840' },
  ATOM:  { github: 'cosmos/cosmos-sdk',                  blog_rss: 'https://medium.com/feed/the-interchain-foundation', coinmarketcal_id: '3794' },
  NEAR:  { github: 'near/nearcore',                      blog_rss: 'https://near.org/blog/rss',                        coinmarketcal_id: '6535' },
  APT:   { github: 'aptos-labs/aptos-core',              twitter: 'Aptos_Network',                                     coinmarketcal_id: '21794' },
  SUI:   { github: 'MystenLabs/sui',                     twitter: 'SuiNetwork',                                        coinmarketcal_id: '20947' },
  INJ:   { github: 'InjectiveLabs/injective-core',       twitter: 'Injective_',                                        coinmarketcal_id: '7226' },
  TIA:   { github: 'celestiaorg/celestia-node',          twitter: 'CelestiaOrg',                                       coinmarketcal_id: '22861' },
  SEI:   { github: 'sei-protocol/sei-chain',             twitter: 'SeiNetwork',                                        coinmarketcal_id: '23149' },
  RNDR:  { github: 'rndrnetwork/rndr',                   twitter: 'rendernetwork',                                     coinmarketcal_id: '5690' },
  FET:   { github: 'fetchai/fetchd',                     twitter: 'Fetch_ai',                                          coinmarketcal_id: '3773' },
  AGIX:  { github: 'singnet/snet-daemon',                twitter: 'singularity_net',                                   coinmarketcal_id: '2424' },
  OCEAN: { github: 'oceanprotocol/ocean-contracts',      twitter: 'oceanprotocol',                                     coinmarketcal_id: '3911' },
  GRT:   { github: 'graphprotocol/graph-node',           blog_rss: 'https://thegraph.com/blog/rss.xml',                coinmarketcal_id: '6719' },
  UNI:   { github: 'Uniswap/v4-core',                   blog_rss: 'https://blog.uniswap.org/rss.xml',                 coinmarketcal_id: '7083' },
  AAVE:  { github: 'aave/aave-v3-core',                 blog_rss: 'https://medium.com/feed/aave',                     coinmarketcal_id: '7278' },
  MKR:   { github: 'makerdao/dss',                       twitter: 'MakerDAO',                                          coinmarketcal_id: '1518' },
  COMP:  { github: 'compound-finance/compound-protocol', twitter: 'compoundfinance',                                   coinmarketcal_id: '5692' },
  SNX:   { github: 'Synthetixio/synthetix',              blog_rss: 'https://blog.synthetix.io/rss/',                   coinmarketcal_id: '2586' },
  CRV:   { github: 'curvefi/curve-contract',             twitter: 'CurveFinance',                                      coinmarketcal_id: '6538' },
  LDO:   { github: 'lidofinance/lido-dao',               blog_rss: 'https://blog.lido.fi/rss/',                        coinmarketcal_id: '8000' },
  RPL:   { github: 'rocket-pool/rocketpool',             twitter: 'Rocket_Pool',                                       coinmarketcal_id: '2943' },
  FXS:   { github: 'FraxFinance/frax-solidity',          twitter: 'fraxfinance',                                       coinmarketcal_id: '6953' },
};
